// @ts-nocheck -- auto generated by docstra
import * as d0 from "../../../content/docs/01-index.mdx?docstra";
import * as d1 from "../../../content/docs/02-installation.mdx?docstra";
import * as d2 from "../../../content/docs/03-quick-start.mdx?docstra";
import * as d3 from "../../../content/docs/04-examples.mdx?docstra";
import * as d4 from "../../../content/docs/05-usage/01-basic.mdx?docstra";
import * as d5 from "../../../content/docs/05-usage/02-advanced.mdx?docstra";
import * as d6 from "../../../content/docs/05-usage/index.mdx?docstra";
import * as d7 from "../../../content/docs/apis/01-index.mdx?docstra";
import * as d8 from "../../../content/docs/apis/02-toast.mdx?docstra";
import * as d9 from "../../../content/docs/apis/03-container.mdx?docstra";
import * as d10 from "../../../content/docs/apis/04-types.mdx?docstra";

export const docs = [
  {
    slug: "",
    path: "01-index.mdx",
    data: {
        metadata: d0.metadata,
        raw: d0.raw,
        tableOfContents: d0.tableOfContents,
        body: d0.body,
        lastUpdated: d0.lastUpdated,
    }
  },
  {
    slug: "installation",
    path: "02-installation.mdx",
    data: {
        metadata: d1.metadata,
        raw: d1.raw,
        tableOfContents: d1.tableOfContents,
        body: d1.body,
        lastUpdated: d1.lastUpdated,
    }
  },
  {
    slug: "quick-start",
    path: "03-quick-start.mdx",
    data: {
        metadata: d2.metadata,
        raw: d2.raw,
        tableOfContents: d2.tableOfContents,
        body: d2.body,
        lastUpdated: d2.lastUpdated,
    }
  },
  {
    slug: "examples",
    path: "04-examples.mdx",
    data: {
        metadata: d3.metadata,
        raw: d3.raw,
        tableOfContents: d3.tableOfContents,
        body: d3.body,
        lastUpdated: d3.lastUpdated,
    }
  },
  {
    slug: "usage/basic",
    path: "05-usage/01-basic.mdx",
    data: {
        metadata: d4.metadata,
        raw: d4.raw,
        tableOfContents: d4.tableOfContents,
        body: d4.body,
        lastUpdated: d4.lastUpdated,
    }
  },
  {
    slug: "usage/advanced",
    path: "05-usage/02-advanced.mdx",
    data: {
        metadata: d5.metadata,
        raw: d5.raw,
        tableOfContents: d5.tableOfContents,
        body: d5.body,
        lastUpdated: d5.lastUpdated,
    }
  },
  {
    slug: "usage",
    path: "05-usage/index.mdx",
    data: {
        metadata: d6.metadata,
        raw: d6.raw,
        tableOfContents: d6.tableOfContents,
        body: d6.body,
        lastUpdated: d6.lastUpdated,
    }
  },
  {
    slug: "apis",
    path: "apis/01-index.mdx",
    data: {
        metadata: d7.metadata,
        raw: d7.raw,
        tableOfContents: d7.tableOfContents,
        body: d7.body,
        lastUpdated: d7.lastUpdated,
    }
  },
  {
    slug: "apis/toast",
    path: "apis/02-toast.mdx",
    data: {
        metadata: d8.metadata,
        raw: d8.raw,
        tableOfContents: d8.tableOfContents,
        body: d8.body,
        lastUpdated: d8.lastUpdated,
    }
  },
  {
    slug: "apis/container",
    path: "apis/03-container.mdx",
    data: {
        metadata: d9.metadata,
        raw: d9.raw,
        tableOfContents: d9.tableOfContents,
        body: d9.body,
        lastUpdated: d9.lastUpdated,
    }
  },
  {
    slug: "apis/types",
    path: "apis/04-types.mdx",
    data: {
        metadata: d10.metadata,
        raw: d10.raw,
        tableOfContents: d10.tableOfContents,
        body: d10.body,
        lastUpdated: d10.lastUpdated,
    }
  }
];
