// @ts-nocheck -- auto generated by docstra
import * as d0 from "../content/api/container.mdx?docstra";
import * as d1 from "../content/api/toast.mdx?docstra";
import * as d2 from "../content/api/types.mdx?docstra";
import * as d3 from "../content/examples.mdx?docstra";
import * as d4 from "../content/index.mdx?docstra";
import * as d5 from "../content/installation.mdx?docstra";
import * as d6 from "../content/quick-start.mdx?docstra";
import * as d7 from "../content/usage/advanced.mdx?docstra";
import * as d8 from "../content/usage/basic.mdx?docstra";

export const docs = [
  {
    slug: "api/container",
    path: "api/container.mdx",
    data: {
        metadata: d0.metadata,
        raw: d0.raw,
        tableOfContents: d0.tableOfContents,
        mdxContent: d0.mdxContent,
        lastUpdated: d0.lastUpdated,
    }
  },
  {
    slug: "api/toast",
    path: "api/toast.mdx",
    data: {
        metadata: d1.metadata,
        raw: d1.raw,
        tableOfContents: d1.tableOfContents,
        mdxContent: d1.mdxContent,
        lastUpdated: d1.lastUpdated,
    }
  },
  {
    slug: "api/types",
    path: "api/types.mdx",
    data: {
        metadata: d2.metadata,
        raw: d2.raw,
        tableOfContents: d2.tableOfContents,
        mdxContent: d2.mdxContent,
        lastUpdated: d2.lastUpdated,
    }
  },
  {
    slug: "examples",
    path: "examples.mdx",
    data: {
        metadata: d3.metadata,
        raw: d3.raw,
        tableOfContents: d3.tableOfContents,
        mdxContent: d3.mdxContent,
        lastUpdated: d3.lastUpdated,
    }
  },
  {
    slug: "index",
    path: "index.mdx",
    data: {
        metadata: d4.metadata,
        raw: d4.raw,
        tableOfContents: d4.tableOfContents,
        mdxContent: d4.mdxContent,
        lastUpdated: d4.lastUpdated,
    }
  },
  {
    slug: "installation",
    path: "installation.mdx",
    data: {
        metadata: d5.metadata,
        raw: d5.raw,
        tableOfContents: d5.tableOfContents,
        mdxContent: d5.mdxContent,
        lastUpdated: d5.lastUpdated,
    }
  },
  {
    slug: "quick-start",
    path: "quick-start.mdx",
    data: {
        metadata: d6.metadata,
        raw: d6.raw,
        tableOfContents: d6.tableOfContents,
        mdxContent: d6.mdxContent,
        lastUpdated: d6.lastUpdated,
    }
  },
  {
    slug: "usage/advanced",
    path: "usage/advanced.mdx",
    data: {
        metadata: d7.metadata,
        raw: d7.raw,
        tableOfContents: d7.tableOfContents,
        mdxContent: d7.mdxContent,
        lastUpdated: d7.lastUpdated,
    }
  },
  {
    slug: "usage/basic",
    path: "usage/basic.mdx",
    data: {
        metadata: d8.metadata,
        raw: d8.raw,
        tableOfContents: d8.tableOfContents,
        mdxContent: d8.mdxContent,
        lastUpdated: d8.lastUpdated,
    }
  }
];
