// @ts-nocheck -- auto generated by docstra
import * as d0 from "../content/index.mdx?docstra";

export const docs = [
  {
    slug: "index",
    path: "index.mdx",
    data: {
        metadata: d0.metadata,
        raw: d0.raw,
        tableOfContents: d0.tableOfContents,
        mdxContent: d0.mdxContent,
        lastUpdated: d0.lastUpdated,
    }
  }
];
